// <auto-generated />
using System;
using ElectronicStudentJournal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicStudentJournal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250730124820_SeedDataTest_1")]
    partial class SeedDataTest_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicStudentJournal.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeName")
                        .HasColumnType("int");

                    b.Property<DateTime>("GradeReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GradeSubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeWeight")
                        .HasColumnType("int");

                    b.Property<bool>("IsGradeVerbal")
                        .HasColumnType("bit");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ElectronicStudentJournal.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PeselNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("StudentId");

                    b.HasIndex("GradeId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = -1,
                            Age = 2,
                            BirthDate = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "testImie",
                            HomeAddress = "ul test",
                            LastName = "testNazwisko",
                            PeselNumber = "1234567891",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            StudentId = -2,
                            Age = 54,
                            BirthDate = new DateTime(1990, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "testImie2",
                            HomeAddress = "ul test",
                            LastName = "testNazwisko2",
                            PeselNumber = "698345671",
                            PhoneNumber = "993456789"
                        });
                });

            modelBuilder.Entity("ElectronicStudentJournal.Models.Student", b =>
                {
                    b.HasOne("ElectronicStudentJournal.Models.Grade", null)
                        .WithMany("Student")
                        .HasForeignKey("GradeId");
                });

            modelBuilder.Entity("ElectronicStudentJournal.Models.Grade", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
